#!/usr/bin/env bash

#
# Connecting to a bluetooth speaker easily
# Author: ricerox
# License: MIT
# Repo: https://github.com/ricerox/littleScripts/
#

if [[ "${1}" == *":"* ]]; then
    device="${1}"
elif [[ "${1}" != "" ]]; then
    device="$(
        bluetoothctl devices |
        grep -i "${1}" |
        cut -d" " -f2
    )"
    deviceCount="$( echo "${device}" | wc -l )"

    if (( deviceCount > 1)); then
        echo >&2 "The device identifier is ambiguous."
        exit 1
    fi
else
    echo >&2 "A device ID must be supplied."
    exit 1
fi

# My raspberry pi doesn't always load this module,
# so in this script we load it manually since the connection doesn't work otherwise.
if ! pactl list modules | grep -i -q "module-bluetooth-discover"; then
    pactl load-module module-bluetooth-discover >/dev/null 2>&1
fi

{
    bluetoothctl power on
    bluetoothctl connect "${device}"
    ret=$?
} >/dev/null

if (( ${ret} != 0 )); then
    echo >&2 "something went wrong while connecting."
    exit 2
else
    echo "Successfully connected to ${device}."
fi

paSocketName="$( pacmd list-sinks | grep -E 'name:|index' | grep -i blue | cut -d"<" -f2 | cut -d">" -f1 )"
pacmd "set-default-sink ${paSocketName}"

if (( $? == 0 )); then
    echo "Successfully set speaker as audio output."
fi
