#!/usr/bin/env bash

#
# Create a list of all ("manually") installed packages
# Author: ricerox
# License: MIT
# Repo: https://github.com/ricerox/littleScripts/
#

# cron executes this as the user so $HOME is actually set
installedPackagesFile="${HOME}/.packagelist"

export LANG=C

pm_apt() {
    apt list --manual-installed | tail -n+2
}
pm_pacman() {
    pacman -Qe
}
pm_pip() {
    pip freeze
}
pm_pipx() {
    pipx list
}
pm_flatpak() {
    flatpak list --app --columns=application,version
}
pm_npm() {
    npm list -g
}

{
    date --iso-8601
    echo "=========="

    while read -r pm; do
        if command -v "${pm}" >/dev/null; then
            echo -e "\n----------\n${pm}\n----------"
            "pm_${pm}"
        fi
    done <<<"$(declare -F | sed -n -E -e '/pm_/ s/.* pm_// p')"
} >"${installedPackagesFile}"
