#!/usr/bin/env bash

#
# Create a list of all ("manually") installed packages
# Author: pixELSflash
# License: MIT
# Repo: https://github.com/pixELSflash/littleScripts/
#

# cron executes this as the user so $HOME is actually set
installedPackagesFile="${HOME}/.packagelist"
[[ ! -f "${installedPackagesFile}" ]] && touch "${installedPackagesFile}"

lastTime="$(head -n1 "${installedPackagesFile}")"
today="$(date --iso-8601)"

if [[ ${lastTime} !=  "${today}" ]]; then
    {
        export LANG=C

        echo -e "${today}\n=========="

        if command -v apt >/dev/null 2>&/dev/null; then
            echo -e "apt\n----------"
            apt list --manual-installed | tail -n+2
        elif command -v pacman >/dev/null 2>&/dev/null; then
            echo -e "pacman\n----------"
            pacman -Qe
        fi

        echo -e "----------\npip\n----------"
        pip freeze

        echo -e "----------\nflatpak\n----------"
        flatpak list --app

    } >"${installedPackagesFile}"
fi
