#!/usr/bin/env bash

#
# Create a list of all ("manually") installed packages
# Author: pixELSflash
# License: MIT
# Repo: https://github.com/pixELSflash/littleScripts/
#

# cron executes this as the user so $HOME is actually set
installedPackagesFile="${HOME}/.installed-packages"
[[ ! -f "${installedPackagesFile}" ]] && touch "${installedPackagesFile}"

lastTime="$(head -n1 "${installedPackagesFile}")"
today="$(date --iso-8601)"

if [[ ${lastTime} !=  "${today}" ]]; then
    echo -ne "${today}\n----------\n" >"${installedPackagesFile}"

    apt list --installed 2>/dev/null |
        tail -n+2 | # remove first line "Listing..."
        grep -v -i -E "\,(automatisch|automatic)\]" >>"${installedPackagesFile}"
fi
