#!/bin/bash

#
# Cycling through audio output devices
# Author: ricerox
# License: MIT
# Repo: https://github.com/ricerox/littleScripts/
#

if [[ "${1}" == "-r" ]] || [[ "${1}" == "--reversed" ]]; then
    reversed="true"
else
    reversed="false"
fi

selected_sink="$( pactl get-default-sink )"
selected_sink_id="$( pactl list short sinks | grep "${selected_sink}" | cut -f1 )"

mapfile -t all_sink_ids < <( pactl list short sinks | cut -f1 )

for i in "${!all_sink_ids[@]}"; do
    if [[ "${all_sink_ids[$i]}" == "${selected_sink_id}" ]]; then
        current_sink_index="${i}"
    fi
done

if ! "${reversed}"; then
    new_index="$(( (current_sink_index + 1) % ${#all_sink_ids[@]} ))"
else
    new_index="$(( (current_sink_index - 1) % ${#all_sink_ids[@]} ))"
fi

new_sink_id="${all_sink_ids[${new_index}]}"
pactl set-default-sink "${new_sink_id}"


mapfile -t all_stream_ids < <( pactl list sink-inputs short | cut -f1 )
for stream_id in "${all_stream_ids[@]}"; do
    pactl move-sink-input "${stream_id}" "${new_sink_id}"
done
