#!/usr/bin/env bash

#
# Get the newest files from a directory of a remote ftp server
# Author: ricerox
# License: MIT
# Repo: https://github.com/ricerox/littleScripts/
#

if [[ "${*}" == *"--help"* ]]; then
    echo "Usage: getnewestfiles host path [amountoffiles]"
    echo ""
    echo "If no argument for amountoffiles is given, it defaults to 1."
    exit 0
fi

if (( $# < 2 )); then
    echo >&2 "Missing arguments."
    echo >&2 "use '--help' for further help."
    exit 1
fi

host="${1}"
path="${2}"
amountOfFiles="${3:-1}"

serverResponse="$( LANG=C curl -s "${host}${path}/" )" # The "/" in the end causes curl to show the index of the directory
curlStatus=$?

if (( ${curlStatus} == 7 )); then
    echo >&2 "The selected destination is not reachable"
    exit 7
elif (( ${curlStatus} == 9 || ${curlStatus} == 78 )); then
    echo >&2 "The selected file does not exist"
    exit "${curlStatus}"
fi

if [[ "${serverResponse}" == "" ]]; then
    echo "There aren't any files in the selected directory"
    exit 3
fi

read -r -d" " -a allFiles <<<"$(
        echo "${serverResponse}" |
        rev | cut -d" " -f1 | rev |
        sort -n
    )"

start=$(( ${#allFiles[@]} - 1 ))
end=$(( start - amountOfFiles ))
for ((i=start; i>end; i--)); do
    currentFile="${allFiles[${i}]}"
    curl --silent "${host}${path}/${currentFile}" -O &&
        echo "Downloaded file: ${currentFile}" ||
        echo "Failed to download: ${currentFile}"
done
