#!/bin/env bash

bookmarkFile="${HOME}/.pathBookmarks"

if (( $# == 0 )) || [[ "${1}" == "--list" ]]; then
    cat "${bookmarkFile}"
    exit
fi

if [[ "${1}" == "--file" ]]; then
    echo "${bookmarkFile}"
    exit
fi

if (( $# == 1 )); then
    searchString="${*}"

    while read -r line; do
        if echo "${line}" | grep -iq -- "${searchString}"; then
            echo "${line}" |
                cut -d":" -f2 |
                cut -b1 --complement # remove leading space
        fi
    done <"${bookmarkFile}"

elif (( $# == 2 )); then
    name="${1}"
    path="$( realpath "${2}" )"

    if (( $# != 0 )); then
        echo >&2 "Cannot add path to bookmarks. The path does not exist"
        exit 1
    fi

    echo "${name} : ${path}" >>"${bookmarkFile}"

elif (( $# > 2 )) || [[ ${*} == *" -h "* ]] || [[ ${*} == *" --help "* ]]; then
    echo "USAGE: $0 { searchPattern | {name} {path} }"
fi
