#!/usr/bin/env bash

#
# Squeeze the output of a command to a single line
# Author: ricerox
# License: MIT
# Repo: https://github.com/ricerox/littleScripts/
#

if [[ ! -p /dev/stdin ]]; then
    echo >&2 "No input supplied via stdin."
    exit 1
fi

COLUMNS="$( tput cols )"

# An alternative would be to first white out the line and then override it
#whiteout="$(printf "%${COLUMNS}s" " ")"
# in while loop:
#echo -ne "\r${whiteout}\r"
#printf "\r%.${COLUMNS}s" "${line}"

while read -r line; do
    printf "\r%-${COLUMNS}.${COLUMNS}s" "${line}"
done <"/dev/stdin"
echo
