#!/usr/bin/env bash

#
# Quickly toggle (or set) Gnome's do not disturb mode
# Author: ricerox
# License: MIT
# Repo: https://github.com/ricerox/littleScripts/
#

enabled="$( gsettings get org.gnome.desktop.notifications show-banners )"

if [[ "${1}" == "on" ]] || [[ "${1}" == "true" ]]; then
    now="false"
elif [[ "${1}" == "off" ]] || [[ "${1}" == "false" ]]; then
    now="true"
else
    now="$( "${enabled}" && echo false || echo true )"
fi

gsettings set org.gnome.desktop.notifications show-banners "${now}"
